name = "pointypal-worker"
main = "src/index.ts"
compatibility_date = "2024-04-03"

[vars]
DEFAULT_CLAUDE_MODEL = "claude-haiku-4-5-20251001"

[env.production.vars]
// DEFAULT_CLAUDE_MODEL = "claude-sonnet-4-5"
DEFAULT_CLAUDE_MODEL = "claude-haiku-4-5-20251001"
DEFAULT_ELEVENLABS_MODEL_ID = "eleven_flash_v2_5"
ELEVENLABS_OUTPUT_FORMAT = "mp3_44100_128"
ALLOWED_ORIGINS = ""